language: generic
sudo: required
services:
  - docker

script:
  - docker build -t mozilla/lua_sandbox_extensions .
  - |
    docker run --rm mozilla/lua_sandbox_extensions \
    bash -c 'cd /root/lua_sandbox_extensions/release && ctest -V -E parquet -C integration'
  - mkdir dist
  - |
    docker run -v `pwd`/dist:/dist --rm mozilla/lua_sandbox_extensions \
    bash -c 'cp /root/lua_sandbox_extensions/release/*.rpm /dist'
  - sha256sum dist/*
